version: "2"
run:
  concurrency: 2
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - fatcontext
    - govet
    - ineffassign
    - perfsprint
    - prealloc
    - staticcheck
    - unused
  settings:
    funlen:
      lines: 80
      statements: 50
    lll:
      line-length: 80
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
